# Copyright © 2022 The Homeport Team
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

.PHONY: default
default: test

.PHONY: all
all: test

.PHONY: clean
clean:
	@rm -rf dist
	@go clean -cache $(shell go list ./...)

.PHONY: todo-list
todo-list:
	@grep -InHR --exclude-dir=vendor --exclude-dir=.git '[T]ODO ' $(shell pwd)

.PHONY: lint
lint:
	@golangci-lint run

.PHONY: misspell
misspell:
	@find . -type f \( -name "*.go" -o -name "*.md" \) -print0 | xargs -0 misspell -error

.PHONY: unit-test
unit-test:
	@go run github.com/onsi/ginkgo/v2/ginkgo \
	  --coverprofile=unit.coverprofile \
	  --randomize-all \
	  --randomize-suites \
	  --fail-on-pending \
	  --keep-going \
	  --slow-spec-threshold=4m \
	  --compilers=2 \
	  --race \
	  --trace \
	  ./...

.PHONY: test
test: lint misspell unit-test

.PHONY: gen-docs
gen-docs:
	rm -f .docs/commands/*.md
	TMPDIR=/tmp go run cmd/gendocs/docs.go
	perl -pi -e "s:$(HOME):~:g" .docs/commands/*.md # omit username in docs
	perl -pi -e 's/\e\[[0-9;]*m//g' .docs/commands/*.md # remove ANSI sequences
	perl -ni -e 'print unless m/^###### Auto generated by/' .docs/commands/*.md # remove generated by line
