name: redis deployment
releases:
- name: redis
  namespace: redis
  location: stable/redis
  before: [echo "$(date) before release"]
  after: [echo "$(date) after release"]

before:
- cmd: /bin/bash
  args:
  - -c
  - |
    #!/bin/bash
    echo "$(date) before deployment"

after:
- echo "$(date) after deployment"
